<a href="https://colab.research.google.com/github/elkamill0/PyTorch-course/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [52]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [53]:
## Introducion to Tensors

## Creating tensors

In [54]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [55]:
scalar.ndim

0

In [56]:
# Get tensor back as Python int
scalar.item()

7

In [57]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [58]:
vector.ndim

1

In [59]:
vector.shape

torch.Size([2])

In [60]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [61]:
MATRIX.ndim

2

In [62]:
MATRIX[1]

tensor([ 9, 10])

In [63]:
MATRIX.shape

torch.Size([2, 2])

In [64]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [65]:
TENSOR.ndim

3

In [66]:
TENSOR.shape

torch.Size([1, 3, 3])

In [67]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [68]:
# scalar - a
# vector - y
# matrix - Q
# tensor - X

### Random tensors

Why random tensors?

In [69]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5128, 0.4068, 0.2829, 0.1280],
        [0.1119, 0.9746, 0.8925, 0.0306],
        [0.6949, 0.8696, 0.7945, 0.8696]])

In [70]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [71]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [72]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [73]:
ones.dtype

torch.float32

In [74]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [75]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [77]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What devide is your tensor on
                               requires_grad=False) # whether or not to track gradients with this operations
float_32_tensor

tensor([3., 6., 9.])

In [78]:
float_32_tensor.dtype

torch.float32

In [79]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [80]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [81]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [82]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`



In [83]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5112, 0.1817, 0.3823, 0.4088],
        [0.6211, 0.8188, 0.6125, 0.5490],
        [0.3283, 0.9891, 0.0609, 0.4416]])

In [84]:
# Find out details aoubt some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5112, 0.1817, 0.3823, 0.4088],
        [0.6211, 0.8188, 0.6125, 0.5490],
        [0.3283, 0.9891, 0.0609, 0.4416]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [90]:
tensor = torch.tensor([1, 2, 3])

# There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [113]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.8501, 0.8704],
        [0.5474, 0.5297]])

In [93]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [94]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [95]:
tensor

tensor([1, 2, 3])

In [96]:
 # Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [106]:
tensor @ tensor   # @ (at) is the Matrix multiplication

tensor(14)

In [104]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.22 ms, sys: 0 ns, total: 1.22 ms
Wall time: 1.13 ms


tensor(14)

In [103]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 1.31 ms, total: 1.31 ms
Wall time: 1.18 ms


tensor(14)

### One of the most common errors in deep learning: shape error

In [116]:
 # Shapes for matrix multiplication
 tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
 tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])
 # torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
 torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [118]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [120]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [121]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A, tensor_B.T)


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])