<a href="https://colab.research.google.com/github/elkamill0/PyTorch-course/blob/main/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2. Create a random tensor with shape `(7, 7)`.

In [2]:
tensor = torch.rand(7,7)
tensor

tensor([[0.6128, 0.1939, 0.5785, 0.1418, 0.2657, 0.8161, 0.9979],
        [0.2291, 0.5320, 0.7127, 0.9209, 0.4355, 0.1529, 0.9411],
        [0.2978, 0.9499, 0.4193, 0.6579, 0.5477, 0.5115, 0.3448],
        [0.1480, 0.1885, 0.4905, 0.5724, 0.2660, 0.0104, 0.2479],
        [0.1890, 0.8556, 0.8079, 0.7477, 0.4557, 0.5646, 0.1887],
        [0.5404, 0.3682, 0.5907, 0.1671, 0.7234, 0.1256, 0.7351],
        [0.5394, 0.9440, 0.3057, 0.0041, 0.0880, 0.9497, 0.3506]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
matrix1 = torch.rand(1,9)
matrix2 = torch.rand(1,9)
torch.mm(matrix1, matrix2.T)

tensor([[1.0230]])

4. Set the random seed to `0` and do exercises 2 & 3 over again.

In [4]:
torch.manual_seed(0)
matrix1 = torch.rand(1,9)
torch.manual_seed(0)
matrix2 = torch.rand(1,9)
print(matrix1 == matrix2)
torch.mm(matrix1, matrix2.T)

tensor([[True, True, True, True, True, True, True, True, True]])


tensor([[2.6097]])

In [5]:
torch.manual_seed(0)
tensor = torch.rand(7,7)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.

In [47]:
tensor = torch.rand(2,3)
tensor = tensor.to("cuda")
torch.manual_seed(1234)
tensor

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [48]:
tensor = torch.tensor(torch.rand(2,3), device="cuda")
torch.manual_seed(1234)
tensor

<ipython-input-48-6dee04cf8e8a>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(torch.rand(2,3), device="cuda")


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).

In [68]:
device = "cuda"
torch.manual_seed(1234)
tensor1 = torch.rand(2, 3)
tensor1 = tensor1.to(device)
tensor2 = torch.rand(2, 3)
torch.manual_seed(1234)
tensor2 = tensor2.to(device)
tensor1, tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [73]:
tensor3 = torch.mm(tensor1.T, tensor2)
tensor3

tensor([[0.1353, 0.0330, 0.2644],
        [0.0330, 0.1649, 0.1453],
        [0.2644, 0.1453, 0.5584]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [75]:
torch.min(tensor3)

tensor(0.0330, device='cuda:0')

9. Find the maximum and minimum index values of the output of 7.

In [76]:
torch.max(tensor3)

tensor(0.5584, device='cuda:0')