<a href="https://colab.research.google.com/github/elkamill0/PyTorch-course/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [8]:
## Introducion to Tensors

## Creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [20]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [21]:
vector.ndim

1

In [22]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [23]:
MATRIX.ndim

2

In [25]:
MATRIX[1]

tensor([ 9, 10])

In [26]:
MATRIX.shape

torch.Size([2, 2])

In [36]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [37]:
TENSOR.ndim

3

In [38]:
TENSOR.shape

torch.Size([1, 3, 3])

In [39]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [40]:
# scalar - a
# vector - y
# matrix - Q
# tensor - X

### Random tensors

Why random tensors?

In [49]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8533, 0.6115, 0.9860, 0.1261],
        [0.2247, 0.3188, 0.2415, 0.9479],
        [0.3683, 0.9914, 0.3916, 0.7095]])

In [51]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [58]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [62]:
ones.dtype

torch.float32